name: smos-report
version: '0.0.0.0'
category: Tool
author: Tom Sydney Kerckhove
maintainer: syd.kerckhove@gmail.com
copyright: ! 'Copyright: (c) 2017 Tom Sydney Kerckhove'
license: AllRightsReserved
homepage: https://github.com/NorfairKing/smos
default-extensions:
- NoImplicitPrelude

dependencies:
- ansi-wl-pprint >=0.6 && <=0.7
- base >=4.9 && <=5
- containers >=0.5 && <0.6
- optparse-applicative >=0.13 && <0.14
- path >=0.5 && <0.6
- path-io >=1.2 && <1.3
- smos-data >=0.0 && <0.1
- text >=1.2 && <1.3
- validity >=0.4 && <0.5
- validity-containers >=0.2 && <0.3
- validity-path >=0.2 && <0.3
- validity-text >=0.2 && <0.3
- validity-time >=0.1 && <0.2
- validity-unordered-containers >=0.1 && <0.2
- yaml >=0.8 && <0.9

library:
  source-dirs: src/
  ghc-options: -Wall
  exposed-modules:
  - Smos.Report
  - Smos.Report.Default
  - Smos.Report.Entry
  - Smos.Report.Entry.Pretty
  - Smos.Report.Entry.Types

executables:
  smos-report:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - smos-report
    default-extensions:
    - ImplicitPrelude

tests:
  smos-report-test:
    main: Spec.hs
    source-dirs: test/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - QuickCheck
    - genvalidity
    - genvalidity-containers
    - genvalidity-hspec
    - genvalidity-hspec-aeson
    - genvalidity-text
    - genvalidity-time
    - genvalidity-unordered-containers
    - hspec
    - smos-data
    - smos-data-gen
    - smos-report
