name: smos-data
version: '0.0.0.0'
category: Tool
author: Tom Sydney Kerckhove
maintainer: syd.kerckhove@gmail.com
copyright: ! 'Copyright: (c) 2017 Tom Sydney Kerckhove'
license: AllRightsReserved
homepage: https://github.com/NorfairKing/smos
default-extensions:
- NoImplicitPrelude

dependencies:
- base >=4.9 && <=5
- aeson >=1.1 && <1.2
- bytestring >=0.10 && <0.11
- containers >=0.5 && <0.6
- hashable  
- path >=0.5 && <0.6
- path-io >=1.2 && <1.3
- text
- time >=1.6 && <1.7
- unordered-containers >=0.2 && <0.3
- validity >=0.4 && <0.5
- validity-containers >=0.2 && <0.3
- validity-text >=0.2 && <0.3
- validity-time >=0.1 && <0.2
- validity-unordered-containers >=0.1 && <0.2
- yaml >=0.8 && <0.9
library:
  source-dirs: src/
  ghc-options: -Wall
  exposed-modules:
  - Smos.Data
  - Smos.Data.Types
