name: smos-data-gen
version: '0.0.0.0'
category: Tool
author: Tom Sydney Kerckhove
maintainer: syd.kerckhove@gmail.com
copyright: ! 'Copyright: (c) 2017 Tom Sydney Kerckhove'
license: AllRightsReserved
homepage: https://github.com/NorfairKing/smos

default-extensions:
- NoImplicitPrelude

dependencies:
- base >=4.9 && <=5
  
library:
  source-dirs: src/
  ghc-options: -Wall
  exposed-modules:
  - Smos.Data.Gen

tests:
  smos-data-gen-test:
    main: Spec.hs
    source-dirs: test/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - smos-data
    - hspec
