name: smos-data-gen
version: '0.0.0.0'
category: Tool
author: Tom Sydney Kerckhove
maintainer: syd.kerckhove@gmail.com
copyright: ! 'Copyright: (c) 2017 Tom Sydney Kerckhove'
license: AllRightsReserved
homepage: https://github.com/NorfairKing/smos

default-extensions:
- NoImplicitPrelude

dependencies:
- base >=4.9 && <=5
- QuickCheck
- genvalidity
- genvalidity-containers
- genvalidity-path
- genvalidity-text
- genvalidity-time
- genvalidity-unordered-containers
- smos-data
  
library:
  source-dirs: src/
  ghc-options: -Wall
  exposed-modules:
  - Smos.Data.Gen
  - Smos.Report.Gen

tests:
  smos-data-test:
    main: Spec.hs
    source-dirs: test/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - genvalidity-hspec
    - genvalidity-hspec-aeson
    - hspec
    - smos-data
    - smos-data-gen
