name: cursor-gen
version: '0.0.0.0'
category: Tool
author: Tom Sydney Kerckhove
maintainer: syd.kerckhove@gmail.com
copyright: ! 'Copyright: (c) 2017 Tom Sydney Kerckhove'
license: AllRightsReserved
homepage: https://github.com/NorfairKing/smos
default-extensions:
- NoImplicitPrelude

dependencies:
- QuickCheck >=2.9 && <2.10
- base >=4.9 && <=5
- bytestring >=0.10 && <0.11
- containers >=0.5 && <0.6
- cursor >=0.0 && <0.1
- genvalidity >=0.4 && <0.5
- genvalidity-containers >=0.3 && <0.4
- genvalidity-hspec >=0.5 && <0.6
- genvalidity-text >=0.4 && <0.5
- hspec >=2.4 && <2.5
- microlens >=0.4 && <0.5
- mtl >=2.2 && <2.3
- safe >=0.3 && <0.4
- text >=1.2 && <1.3
- unordered-containers >=0.2 && <0.3
- validity >=0.4 && <0.5
- validity-containers >=0.2 && <0.3
- validity-text >=0.2 && <0.3
- validity-unordered-containers >=0.1 && <0.2

library:
  source-dirs: src/
  ghc-options: -Wall
  exposed-modules:
  - Cursor.TestUtils
  - Cursor.List.Gen
  - Cursor.ListElem.Gen
  - Cursor.Text.Gen
  - Cursor.TextField.Gen
  - Cursor.Tree.Gen

tests:
  cursor-test:
    main: Spec.hs
    source-dirs: test/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - QuickCheck
    - cursor
    - cursor-gen
    - genvalidity
    - genvalidity-containers
    - genvalidity-hspec
    - genvalidity-text
    - hspec

