name: smos
version: '0.0.0.0'
category: Tool
author: Tom Sydney Kerckhove
maintainer: syd.kerckhove@gmail.com
copyright: ! 'Copyright: (c) 2017 Tom Sydney Kerckhove'
license: AllRightsReserved
homepage: https://github.com/NorfairKing/smos
default-extensions:
- NoImplicitPrelude

dependencies:
- base >=4.9 && <=5
- brick >=0.28 && <0.29
- bytestring >=0.10 && <0.11
- containers >=0.5 && <0.6
- mtl >=2.2 && <2.3
- path >=0.5 && <0.6
- path-io >=1.2 && <1.3
- safe >=0.3 && <0.4
- smos-data >=0.0 && <0.1
- time >=1.6 && <1.7
- text >=1.2 && <1.3
- unordered-containers >=0.2 && <0.3
- validity >=0.4 && <0.5
- validity-containers >=0.2 && <0.3
- validity-text >=0.2 && <0.3
- validity-time >=0.1 && <0.2
- validity-unordered-containers >=0.1 && <0.2
- vty >=5.18 && <5.19

library:
  source-dirs: src/
  ghc-options: -Wall
  exposed-modules:
  - Smos
  - Smos.Actions
  - Smos.Cursor
  - Smos.Default
  - Smos.TextCursor
  - Smos.Types

executables:
  smos:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - smos
    default-extensions:
    - ImplicitPrelude

tests:
  smos-test:
    main: Spec.hs
    source-dirs: test/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - QuickCheck
    - genvalidity
    - genvalidity-containers
    - genvalidity-hspec
    - genvalidity-hspec-aeson
    - genvalidity-text
    - genvalidity-time
    - genvalidity-unordered-containers
    - hspec
    - smos
    - smos-data
    - smos-data-gen

