name: smos
version: '0.0.0.0'
category: Tool
author: Tom Sydney Kerckhove
maintainer: syd.kerckhove@gmail.com
copyright: ! 'Copyright: (c) 2017 Tom Sydney Kerckhove'
license: AllRightsReserved
homepage: https://github.com/NorfairKing/smos
default-extensions:
- NoImplicitPrelude

dependencies:
- base >=4.9 && <=5
- path >=0.5 && <0.6
- path-io >=1.2 && <1.3
- smos-data >=0.0 && <0.1
- validity >=0.4 && <0.5
- validity-containers >=0.2 && <0.3
- validity-text >=0.2 && <0.3
- validity-time >=0.1 && <0.2
- validity-unordered-containers >=0.1 && <0.2
- brick >=0.28 && <0.29
- vty >=5.18 && <5.19

library:
  source-dirs: src/
  ghc-options: -Wall
  exposed-modules:
  - Smos

executables:
  smos:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - smos
    default-extensions:
    - ImplicitPrelude
